#!/bin/bash
#
# generate-package-configs.sh – generates mkosi package configs from .txt files.
#
# Usage:
#   VARIANT=full ./generate-package-configs.sh
#   VARIANT=hyprland ./generate-package-configs.sh
#   VARIANT=base ./generate-package-configs.sh
#
# Output: images/mkosi.conf.d/packages.conf
#
set -e

VARIANT="${VARIANT:-full}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ── Validate variant ──────────────────────────────────────────────────
case "$VARIANT" in
    base|hyprland|full) ;;
    *)
        echo "ERROR: Unknown variant '$VARIANT'. Use: base, hyprland, full"
        exit 1
        ;;
esac

# ── Load AUR-only skip list ───────────────────────────────────────────
# Packages in chaotic-aur.txt are installed via mkosi.postinst.chroot
# (after Chaotic-AUR is configured), NOT during mkosi's initial install.
AUR_SKIP="$SCRIPT_DIR/packages/chaotic-aur.txt"
declare -A SKIP_PKGS=()
if [ -f "$AUR_SKIP" ]; then
    while IFS= read -r line; do
        pkg="${line%%#*}"
        pkg="${pkg// /}"
        [ -z "$pkg" ] && continue
        SKIP_PKGS["$pkg"]=1
    done < "$AUR_SKIP"
fi

# ── Collect package files ─────────────────────────────────────────────
PACKAGE_FILES=(
    "$SCRIPT_DIR/packages/base.txt"
    "$SCRIPT_DIR/packages/immutable.txt"
)

case "$VARIANT" in
    base)     ;; # no extra packages
    hyprland) PACKAGE_FILES+=("$SCRIPT_DIR/packages/hyprland.txt") ;;
    full)  PACKAGE_FILES+=("$SCRIPT_DIR/packages/full.txt") ;;
esac

# ── Generate packages.conf ────────────────────────────────────────────
mkdir -p "$SCRIPT_DIR/mkosi.conf.d"
CONF="$SCRIPT_DIR/mkosi.conf.d/packages.conf"

cat > "$CONF" <<-EOF
	# Generated by generate-package-configs.sh
	# VARIANT=$VARIANT
	# DO NOT EDIT – changes will be overwritten

	[Content]
EOF

PKG_COUNT=0
SKIP_COUNT=0
for FILE in "${PACKAGE_FILES[@]}"; do
    while IFS= read -r line; do
        # Strip whitespace, skip comments and blanks
        pkg="${line%%#*}"
        pkg="${pkg// /}"
        [ -z "$pkg" ] && continue
        # Skip AUR-only packages (installed via postinst)
        if [ "${SKIP_PKGS[$pkg]}" = "1" ]; then
            : $(( SKIP_COUNT += 1 ))
            continue
        fi
        echo "Packages=$pkg" >> "$CONF"
        : $(( PKG_COUNT += 1 ))
    done < "$FILE"
done

echo "→ Generated $CONF"
echo "  Variant:  $VARIANT"
echo "  Packages: $PKG_COUNT (skipped $SKIP_COUNT AUR-only)"
