[Distribution]
Distribution=arch
Release=latest
RepositoryKeyCheck=no

[Output]
Format=oci
OutputDirectory=output
ImageId=omar

[Content]
PackageDirectories=packages
Packages=@base.txt
Packages=@immutable.txt
Bootloader=systemd-boot
Bootable=yes
UnifiedKernelImages=yes
ExtraTrees=mkosi.extra
Locale=en_US.UTF-8
Timezone=UTC
Keymap=us
Hostname=omar

[Build]
ToolsTree=default
ToolsTreePackages=archlinux-keyring
CacheDirectory=mkosi.cache
BuildDirectory=mkosi.builddir
Incremental=yes
WithNetwork=yes
