[Distribution]
Distribution=arch
Release=latest

[Output]
Format=oci
OutputDirectory=output

[Content]
Packages=@base,@hyprland,@omarchy
PackagesDirectory=packages
Bootloader=systemd-boot
Bootable=yes
UnifiedKernelImages=yes
ExtraTrees=mkosi.extra
Locale=en_US.UTF-8
Timezone=UTC
Keymap=us
Hostname=omar

[Host]
ToolsTree=default
CacheDirectory=mkosi.cache
BuildDirectory=mkosi.builddir
Incremental=yes
